//
//  types.ts
//  ChiEAC
//
//  TypeScript type definitions for TeamManager components
//  Created by Shivaang Kumar on 8/17/25.
//

export interface Team {
  id: string;
  team_name: string;
  team_code: string;
  team_description: string;
  order: number;
}

export interface TeamMember {
  id: string;
  member_name: string;
  member_title: string;
  member_team: string;
  member_summary: string;
  member_summary_short: string;
  member_image_link?: string;
  order: number;
  // Legacy compatibility fields
  name?: string;
  title?: string;
  bio?: string;
  bioShort?: string;
  team?: string;
  imageURL?: string;
}

export interface AutoGeneratedFields {
  team_code: string;
  id: string;
}

export interface MemberAutoGeneratedFields {
  id: string;
  member_team: string;
}

export interface PendingCreation {
  type: 'team' | 'member';
  data: any;
}

export interface PendingDeletion {
  team: Team | null;
  affectedMembers: TeamMember[];
}

export interface ChangeItem {
  field: string;
  oldValue: string;
  newValue: string;
}

export interface PendingChanges {
  type: 'team' | 'member';
  original: Team | TeamMember;
  updated: any;
  changes: ChangeItem[];
}

export interface DuplicateTeamData {
  existingTeam: Team | null;
  newTeamData: any;
}

export type ViewType = 'teams' | 'members';
