//
//  TeamForm.tsx
//  ChiEAC
//
//  Professional team creation/editing form with expert mode
//  Created by Shivaang Kumar on 8/17/25.
//

import React from 'react';
import type { Team } from '../types';

interface TeamFormProps {
  isVisible: boolean;
  editingTeam: Team | null;
  teamFormData: {
    team_name: string;
    team_description: string;
  };
  autoGeneratedFields: {
    team_code: string;
    id: string;
  };
  editingTeamFirestoreFields: boolean;
  onSubmit: (e: React.FormEvent) => void;
  onTeamNameChange: (name: string) => void;
  onTeamDescriptionChange: (description: string) => void;
  onClose: () => void;
  onExpertModeToggle: () => void;
  onDisableExpertMode: () => void;
}

export const TeamForm: React.FC<TeamFormProps> = ({
  isVisible,
  editingTeam,
  teamFormData,
  autoGeneratedFields,
  editingTeamFirestoreFields,
  onSubmit,
  onTeamNameChange,
  onTeamDescriptionChange,
  onClose,
  onExpertModeToggle,
  onDisableExpertMode
}) => {
  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-slate-900 rounded-2xl border border-slate-700 shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <h3 className="font-semibold text-white text-xl">
              {editingTeam ? 'Edit Team' : 'Add New Team'}
            </h3>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 hover:text-white flex items-center justify-center transition-all duration-300"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <form onSubmit={onSubmit} className="space-y-6">
            {/* User Editable Fields */}
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Team Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  value={teamFormData.team_name}
                  onChange={(e) => onTeamNameChange(e.target.value)}
                  className="w-full px-4 py-3 bg-slate-800/50 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                  placeholder="Enter team name"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">
                  Team Description <span className="text-red-400">*</span>
                </label>
                <textarea
                  value={teamFormData.team_description}
                  onChange={(e) => onTeamDescriptionChange(e.target.value)}
                  className="w-full px-4 py-3 bg-slate-800/50 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                  placeholder="Enter team description"
                  rows={4}
                  required
                />
              </div>
            </div>

            {/* Expert Mode Section */}
            {!editingTeam && (
              <div className="p-4 bg-slate-800/50 rounded-lg border border-slate-600">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex-1 mr-4">
                    <div className="font-medium text-slate-300 mb-1">Expert Mode</div>
                    <div className="text-sm text-slate-400">Edit Firestore fields directly (Advanced)</div>
                  </div>
                  <button
                    type="button"
                    onClick={editingTeamFirestoreFields ? onDisableExpertMode : onExpertModeToggle}
                    className={`px-5 py-2.5 rounded-lg font-medium transition-all duration-300 shadow-lg flex items-center gap-2 text-sm ${
                      editingTeamFirestoreFields
                        ? 'bg-gradient-to-r from-red-500 to-red-600 text-white hover:from-red-600 hover:to-red-700 shadow-red-500/25'
                        : 'bg-gradient-to-r from-slate-600 to-slate-700 text-slate-200 hover:from-slate-500 hover:to-slate-600 shadow-slate-700/25 border border-slate-500/30'
                    }`}
                  >
                    {editingTeamFirestoreFields ? (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                        Safe Mode
                      </>
                    ) : (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        Expert Mode
                      </>
                    )}
                  </button>
                </div>

                {/* Auto-generated fields preview */}
                <div className="space-y-3">
                  <div className="flex items-center gap-2 text-sm">
                    <span className="text-slate-400 w-24">Team Code:</span>
                    <span className="text-orange-400 font-mono">
                      {autoGeneratedFields.team_code || 'Will be generated...'}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <span className="text-slate-400 w-24">Document ID:</span>
                    <span className="text-blue-400 font-mono">
                      {autoGeneratedFields.id || 'Will be generated...'}
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Form Actions */}
            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-700">
              <button
                type="button"
                onClick={onClose}
                className="px-6 py-2.5 bg-slate-700 hover:bg-slate-600 text-slate-200 font-medium rounded-lg transition-all duration-300"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-6 py-2.5 bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-400 hover:to-amber-400 text-white font-medium rounded-lg transition-all duration-300 shadow-lg shadow-orange-500/30"
              >
                {editingTeam ? 'Update Team' : 'Create Team'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};
